# name: archive-bot-go
# on:
#     push:
#         branches:
#             - master
#     schedule:
#         - cron: '* */6 * * *'
# jobs:
#     build:
#         name: Build
#         runs-on: ubuntu-latest
#         steps:
#             - name: Set up Go 1.14
#               uses: actions/setup-go@v1
#               with:
#                   go-version: 1.14
#               id: go

#             - name: Check out source code
#               uses: actions/checkout@v1

#             - name: Build
#               run: go build .

#             - name: Run
#               run: ./archive-bot -bot-token=${{secrets.ARCHIVE_BOT_TOKEN}} -telegraph-token=${{secrets.ARCHIVE_TELEGRAPH_TOKEN}}
